backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'
media_folder: static/img
public_folder: /img
collections:
  - name: pages
    label: Pages
    files:
      - file: src/pages/layout.md
        label: Layout
        name: layout
        fields:
          - label: Title
            name: title
            widget: hidden
            default: Layout
          - label: Background Image
            name: backgroundImage
            widget: image
          - label: Logo
            name: logoImage
            widget: image
          - label: Logo Alt Text
            name: logoImageAlt
            widget: string
          - label: Heading Image
            name: headingImage
            widget: image
          - label: Heading Image Alt Text
            name: headingImageAlt
            widget: string
          - label: Navigation Links
            name: links
            widget: list
            fields:
              - label: Link Text
                name: linkText
                widget: string
              - label: Link Path
                name: linkPath
                widget: string
          - label: Footer Testimonial Quote Image
            name: quoteImage
            widget: image
          - label: Footer Testimonial
            name: testimonial
            widget: text
          - label: Footer Testimonial Attribution
            name: testimonialAttribution
            widget: string
          - label: Footer Social Heading
            name: socialHeadingImage
            widget: image
          - label: Footer Social Heading Alt Text
            name: socialHeadingImageAlt
            widget: string
          - label: Footer Social Link
            name: socialHeadingHref
            widget: string
          - label: Footer Social Images
            name: socialImages
            widget: list
            fields:
              - label: Image
                name: image
                widget: image
              - label: Link
                name: href
                widget: string
          - label: Copyright
            name: copyright
            widget: string
      - file: src/pages/index.md
        label: Landing Page
        name: index
        fields:
          - label: Template Key
            name: templateKey
            widget: hidden
            default: IndexPage
          - label: Title
            name: title
            widget: string
          - label: Search Engine Description
            name: description
            widget: text
          - label: Yoga Image
            name: yogaImage
            widget: image
          - label: Yoga Blurb
            name: yogaBlurb
            widget: text
          - label: Tea Image
            name: teaImage
            widget: image
          - label: Tea Blurb
            name: teaBlurb
            widget: text
          - label: Good Company Image
            name: goodCompanyImage
            widget: image
          - label: Good Company Blurb
            name: goodCompanyBlurb
            widget: text
      - file: src/pages/schedule.md
        label: Schedule
        name: schedule
        fields:
          - label: Template Key
            name: templateKey
            widget: hidden
            default: SchedulePage
          - label: Title
            name: title
            widget: string
          - label: Search Engine Description
            name: description
            widget: text
      - file: src/pages/intro.md
        label: Intro
        name: intro
        fields:
          - label: Template Key
            name: templateKey
            widget: hidden
            default: MarkdownPage
          - label: Title
            name: title
            widget: string
          - label: Search Engine Description
            name: description
            widget: text
          - label: Body
            name: body
            widget: markdown
      - file: src/pages/teachers.md
        label: Teachers
        name: teachers
        fields:
          - label: Template Key
            name: templateKey
            widget: hidden
            default: TeachersPage
          - label: Title
            name: title
            widget: string
          - label: Search Engine Description
            name: description
            widget: text
          - label: Teachers
            name: teachers
            widget: list
            fields:
              - label: Name
                name: teacherName
                widget: string
              - label: Bio
                name: teacherBio
                widget: markdown
              - label: Photo
                name: teacherImage
                widget: image
