backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'
media_folder: static/img
public_folder: /img
collections:
  - name: layout
    label: Layout
    files:
      - file: src/data/layout.md
        label: Layout
        name: layout
        fields:
          - label: Title
            name: title
            widget: hidden
            default: Layout
          - label: Background Image
            name: backgroundImage
            widget: image
          - label: Logo
            name: logoImage
            widget: image
          - label: Logo Alt Text
            name: logoImageAlt
            widget: string
          - label: Heading Image
            name: headingImage
            widget: image
          - label: Heading Image Alt Text
            name: headingImageAlt
            widget: string
          - label: Navigation Links
            name: links
            widget: list
            fields:
              - label: Link Text
                name: linkText
                widget: string
              - label: Link Path
                name: linkPath
                widget: string
          - label: Footer Quote Image
            name: quoteImage
            widget: image
          - label: Footer Quote
            name: quote
            widget: text
          - label: Footer Quote Attribution
            name: quoteAttribution
            widget: string
          - label: Footer Social Heading
            name: socialHeadingImage
            widget: image
          - label: Footer Social Heading Alt Text
            name: socialHeadingImageAlt
            widget: string
          - label: Footer Social Link
            name: socialHeadingHref
            widget: string
          - label: Footer Social Images
            name: socialImages
            widget: list
            fields:
              - label: Image
                name: image
                widget: image
              - label: Link
                name: href
                widget: string
              - label: Text
                name: text
                widget: string
              - label: Logo
                name: logo
                widget: select
                options: ["Instagram", "Facebook"]
          - label: Copyright
            name: copyright
            widget: string
  - name: customPages
    label: Custom Page
    files:
      - file: src/data/customPages/index.md
        label: Landing Page
        name: index
        fields:
          - label: Template Key
            name: templateKey
            widget: hidden
            default: IndexPage
          - label: Path
            name: path
            widget: hidden
            default: /
          - label: Title
            name: title
            widget: string
          - label: Search Engine Description
            name: description
            widget: text
          - label: Yoga Image
            name: yogaImage
            widget: image
          - label: Yoga Blurb
            name: yogaBlurb
            widget: text
          - label: Tea Image
            name: teaImage
            widget: image
          - label: Tea Blurb
            name: teaBlurb
            widget: text
          - label: Good Company Image
            name: goodCompanyImage
            widget: image
          - label: Good Company Blurb
            name: goodCompanyBlurb
            widget: text
      - file: src/data/customPages/schedule.md
        label: Schedule
        name: schedule
        fields:
          - label: Template Key
            name: templateKey
            widget: hidden
            default: SchedulePage
          - label: Path
            name: path
            widget: string
          - label: Title
            name: title
            widget: string
          - label: Search Engine Description
            name: description
            widget: text
      - file: src/data/customPages/team.md
        label: Team
        name: team
        fields:
          - label: Template Key
            name: templateKey
            widget: hidden
            default: TeamPage
          - label: Path
            name: path
            widget: string
          - label: Title
            name: title
            widget: string
          - label: Search Engine Description
            name: description
            widget: text
          - label: Members
            name: members
            widget: list
            fields:
              - label: Name
                name: memberName
                widget: string
              - label: Bio
                name: memberBio
                widget: markdown
              - label: Photo
                name: memberImage
                widget: image
  - name: basicPages
    label: Basic Page
    folder: src/data/basicPages
    create: true
    fields:
      - label: Template Key
        name: templateKey
        widget: hidden
        default: MarkdownPage
      - label: Path (The part after the domain in the URL)
        name: path
        widget: string
      - label: Title
        name: title
        widget: string
      - label: Search Engine Description
        name: description
        widget: text
      - label: Body
        name: body
        widget: markdown
